name: specbolt CI
on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'
      - name: Install Conan
        uses: turtlebrowser/get-conan@main
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1"
     - name: Install dependencies
        run: |
          conan install . --build=missing
          conan install . --build=missing --settings build_type=Debug
      - name: Build
        run: |
          cmake . --preset=conan-release
          cmake --build --preset=conan-release
          cmake --build --target test --preset=conan-release
