name: specbolt CI
on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'
      - name: install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
      - name: Build
        run: |
          env CC=clang CXX=clang++ cmake . --preset=conan-release
          cmake --build --preset=conan-release
          cmake --build --target test --preset=conan-release
